### ISSUE TITLE
what is Weighted sum？

### ISSUE THREAD

**Issue by vaerdu** [prakharg24/yoloret#3]
Does Weighted sum add the channel of the feature map obtained after 1x1 convolution or add each pixel of the feature map?

**Comment by prakharg24** [comment]
Add each pixel of the feature map.

The aim of the 1x1 conv along with the downsampling/upsampling is to bring all feature maps to the exact same shape in all dimensions. Once that is done, we can simply do a weighted sum for each individual element in the feature map across various scales. I hope that clarifies things.

Check the implementation of weighted sum if you need more details : https://github.com/prakharg24/yoloret/blob/main/code/yolo3/model.py#L119

**Comment by vaerdu** [comment]
> Add each pixel of the feature map.
> 
> The aim of the 1x1 conv along with the downsampling/upsampling is to bring all feature maps to the exact same shape in all dimensions. Once that is done, we can simply do a weighted sum for each individual element in the feature map across various scales. I hope that clarifies things.
> 
> Check the implementation of weighted sum if you need more details : https://github.com/prakharg24/yoloret/blob/main/code/yolo3/model.py#L119

thank you for your reply
