### ISSUE TITLE
Can you publish weight files about MobileNetV2?Thanks

### ISSUE THREAD

**Issue by cacheee** [prakharg24/yoloret#4]

**Comment by prakharg24** [comment]
Hi @cacheee ,

We are working on supplying more weights into the repo. I have been busy with my exams and will work on it during my vacations. You can expect not only the mobilenetv2 weight which we discuss in the paper, but even more models added to the repo soon.

Additionally, our model training does not rely on any significant training tricks and if you want to you can easily replicate it from the instructions provided in the repo. The reason being that we didn't want to emphasize too much on the final absolute value of accuracy and instead focus on the improvements our RFCR module provides.

Hope that helps. I'll add updates to this issue when I add new trained models.

**Comment by cacheee** [comment]
Thank you, I am looking forward to it and wish you success in the exam.
