### ISSUE TITLE
The Question about whether use FLOAT 16 or INT 8 when testing FPS.

### ISSUE THREAD

**Issue by cacheee** [prakharg24/yoloret#6]
In the tabular data mentioned in this paper, are the FPS of YOLO-RET model  all tested by FLOAT 16 quantification?You mentioned in your paper that "We also provide FPS values for TensorRT based INT8 optimizations, to provide a fair comparison against baseline models designed specifically for integer computations", do not understand what it means. Hope you can help me to solve my confusion,thanks!

**Comment by prakharg24** [comment]
Hi @cacheee 
I can understand the confusion. All YOLO-ReT results in the paper are FP16 optimization with TensirRT. However certain baseline models like YOLONano were designed for INT8 optimization and thus we use the INT8 latency values of those baseline models to allow proper comparison. I hope that clarifies things

**Comment by cacheee** [comment]
Therefore, FP16 of YOLO RET was compared with INT8 of YOLO NANO,right? I also want to ask, does FPS calculation only include network infer time, or also include post-processing and image input process?Does the size of the model refer to the quantized size of FP16?Thanks

**Comment by prakharg24** [comment]
Yes.
It includes all pre processing and post processing time too.
No. Original 32 bit model size for yolo-ret models. For the baseline models, the values were copied from respective papers

**Comment by cacheee** [comment]
Thanks!You solved my problem very well.
